import type { EstadoTramite, TipoEvento } from '../types'

export const PROVINCIAS_DATA = [
  { value: 'Azuay', label: 'Azuay', cantones: [
    'Camilo Ponce Enríquez',
    'Cuenca',
    'Gualaceo',
    'Pucará',
    'Sigsig',
  ] },
  { value: 'Bolívar', label: 'Bolívar', cantones: [
    'Chillanes',
    'Chimbo',
    'Echeandía',
    'Guaranda',
    'San Miguel',
  ] },
  { value: 'Cañar', label: 'Cañar', cantones: [
    'Azogues',
    'Cañar',
    'La Troncal',
    'Suscal',
  ] },
  { value: 'Carchi', label: 'Carchi', cantones: [
    'Bolivar',
    'Espejo',
    'Mira',
    'Montúfar',
    'Tulcán',
  ] },
  { value: 'Chimborazo', label: 'Chimborazo', cantones: [
    'Alausi',
    'Chambo',
    'Guamote',
    'Guano',
    'Penipe',
    'Riobamba',
  ] },
  { value: 'Cotopaxi', label: 'Cotopaxi', cantones: [
    'Latacunga',
    'Pangua',
    'Pujilí',
    'Salcedo',
  ] },
  { value: 'El Oro', label: 'El Oro', cantones: [
    'Arenillas',
    'Chilla',
    'El Guabo',
    'La Lajas',
    'Las Lajas',
    'Machala',
    'Pasaje',
    'Piñas',
    'Portovelo',
    'Santa Rosa',
  ] },
  { value: 'Esmeraldas', label: 'Esmeraldas', cantones: [
    'Eloy Alfaro',
    'Esmeraldas',
    'Muisne',
    'Quinindé',
  ] },
  { value: 'Galápagos', label: 'Galápagos', cantones: [
    'San Cristóbal',
    'Santa Cruz',
  ] },
  { value: 'Guayas', label: 'Guayas', cantones: [
    'Alfredo Baquerizo Moreno',
    'Alfredo Baquerizo Moreno (juján)',
    'Balzar',
    'Colimes',
    'Daule',
    'Duran',
    'El Empalme',
    'El Triunfo',
    'Guayaquil',
    'Isidro Ayora',
    'Lomas De Sargentillo',
    'Milagro',
    'Naranjal',
    'Naranjito',
    'Nobol',
    'Pedro Carbo',
    'Salitre',
    'Salitre (urbina Jado)',
    'Samborondon',
    'San Jacinto De Yaguachi',
    'Santa Lucia',
    'Simón Bolívar',
  ] },
  { value: 'Imbabura', label: 'Imbabura', cantones: [
    'Antonio Ante',
    'Cotacachi',
    'Ibarra',
    'Otavalo',
    'Pimampiro',
    'San Miguel De Urcuquí',
  ] },
  { value: 'Loja', label: 'Loja', cantones: [
    'Calvas',
    'Catamayo',
    'Celica',
    'Chaguarpamba',
    'Espindola',
    'Gonzanama',
    'Macará',
    'Olmedo',
    'Paltas',
    'Pindal',
    'Puyango',
    'Quilanga',
    'Sapotillo',
    'Sozoranga',
    'Zapotillo',
  ] },
  { value: 'Los Ríos', label: 'Los Ríos', cantones: [
    'Baba',
    'Babahoyo',
    'Mocache',
    'Montalvo',
    'Palenque',
    'Puebloviejo',
    'Quinsaloma',
    'Urdaneta',
    'Valencia',
    'Ventanas',
    'Vínces',
  ] },
  { value: 'Manabí', label: 'Manabí', cantones: [
    '24 De Mayo',
    '25 De Mayo',
    'Bolivar',
    'Chone',
    'El Carmen',
    'Flavio Alfaro',
    'Jama',
    'Jipijapa',
    'Junín',
    'Montecristi',
    'Olmedo',
    'Paján',
    'Pajancampozano',
    'Pichincha',
    'Portoviejo',
    'Rocafuerte',
    'San Vicente',
    'Santa Ana',
    'Sucre',
    'Tosagua',
  ] },
  { value: 'Morona Santiago', label: 'Morona Santiago', cantones: [
    'Huamboya',
    'Tiwintza',
  ] },
  { value: 'Napo', label: 'Napo', cantones: [
    'Archidona',
    'El Chaco',
    'Quijos',
    'Tena',
  ] },
  { value: 'Orellana', label: 'Orellana', cantones: [
    'La Joya De Los Sachas',
    'Loreto',
  ] },
  { value: 'Pastaza', label: 'Pastaza', cantones: [
    'Pastaza',
  ] },
  { value: 'Pichincha', label: 'Pichincha', cantones: [
    'Cayambe',
    'Distrito Metropolitano De Quito',
    'Mejia',
    'Pedro Moncayo',
    'Puerto Quito',
    'Quito',
    'Rumiñahui',
  ] },
  { value: 'Santa Elena', label: 'Santa Elena', cantones: [
    'Santa Elena',
  ] },
  { value: 'Sucumbíos', label: 'Sucumbíos', cantones: [
    'Cuyabeno',
    'Lago Agrio',
    'Putumayo',
    'Shushufindi',
  ] },
  { value: 'Tungurahua', label: 'Tungurahua', cantones: [
    'Ambato',
    'Patate',
    'Quero',
    'Santiago De Píllaro',
    'Tisaleo',
  ] },
  { value: 'Zamora Chinchipe', label: 'Zamora Chinchipe', cantones: [
    'Centinela Del Cóndor',
    'Chinchipe',
    'El Pangui',
    'Palanda',
    'Yantzaza',
    'Zamora',
  ] },
] as const

export const CULTIVOS = [
  'Aguacate',
  'Algodon Urpima',
  'Arroz',
  'Arveja',
  'Banano',
  'Banano Mantenimiento',
  'Brócoli',
  'Cacao',
  'Cacao - Plátano',
  'Cacao+platano',
  'Café',
  'Caña De Azúcar Formación',
  'Cebada',
  'Cebolla Colorada',
  'Cebolla Perla',
  'Frejol',
  'Fréjol Arbustivo',
  'Fréjol Voluble',
  'Haba',
  'Maiz Suave',
  'Maiz Suave + Arveja',
  'Mani',
  'Maíz - Arverja',
  'Maíz - Frejol',
  'Maíz Duro',
  'Maíz Suave+arveja',
  'Maíz Suave+frejol',
  'Maíz Suave+haba',
  'Palma Africana',
  'Papa',
  'Pimiento',
  'Pitahaya',
  'Pitahaya Mantenimiento',
  'Piña',
  'Piña Formacion',
  'Plátano',
  'Quinua',
  'Soya',
  'Tomate De Arbol Mantenimiento',
  'Tomate De árbol',
  'Tomate Hortícola Campo Abierto',
  'Trigo',
] as const

export const TIPOS_EVENTO: TipoEvento[] = [
  'Inundación',
  'Exceso de humedad',
  'Sequía',
  'Granizo',
  'Helada',
  'Plaga',
  'Enfermedad',
  'Viento',
  'Deslizamiento',
  'Taponamiento',
  'Incendio',
]

export const ESTADOS_TRAMITE: EstadoTramite[] = [
  'Inspeccionado', 'Pendiente', 'En proceso', 'Rechazado', 'Aprobado',
]

export const ANIOS = ['2022', '2023', '2024', '2025', '2026'] as const

export const CHART_COLORS = [
  '#014d1d', '#006b28', '#15803d', '#16a34a', '#22c55e',
  '#4ade80', '#086429', '#0d9a38', '#1a7b35', '#2d8a4e',
] as const
